name: on release

on:
  release:
    types: [created]

jobs:
  publish-github-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Enable corepack
        run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com/'
          cache: 'yarn'
          scope: '@BigE'
      - name: Configure Yarn Authentication
        run: |
          echo "npmRegistries:" >> ./.yarnrc.yml
          echo "  '//npm.pkg.github.com':" >> ./.yarnrc.yml
          echo "    npmAuthToken: ${{ secrets.GITHUB_TOKEN }}" >> ./.yarnrc.yml
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build project
        run: yarn build
      - name: Publish project
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
